### ISSUE TITLE
Modules - Cannot turn off 'Backlog' Module once Enabled

### ISSUE THREAD

**Issue by barryoneill** [taigaio/taiga-front#1037]
I started with a Kanban board.  While exploring the modules settings, once I enabled the 'Backlog' Module, I found I couldn't disable it. 

- go to the project settings for a Kanban project.
- go to _project_ -> _modules_
- Enable *Backlog*.  See that Taiga reports the setting saved.
- Leave the _modules_ tab, but then revisit it.
- Disable *Backlog*, Again, see that taiga reports the setting saved.
- Leave the _modules_ tab, but then revisit it.
- This time, see that *Backlog* is still enabled (and is still visible back in the project view).

**Comment by superalex** [comment]
Hello @barryoneill 

Yesterday we released a fix for this one so it shouldn't be happening in tree.taiga.io (with the last stable release). Is this happening on your own instance?, if that's the point you should update taiga-back to the last stable release. 

Regards,

**Comment by barryoneill** [comment]
Thanks for the fast reply, @superalex .  I can confirm that it's fixed if I use chrome, but I'm still seeing the problem in Safari (I've cleared my cache - but it could still be local to me).   Either way, I'm able to turn it off.  Thank you!

**Comment by superalex** [comment]
Hello @barryoneill 

It's strange that it's only happening in Safari, could you please check if it's still happening?

**Comment by macszur-mob** [comment]
Hi @superalex I'm able to see this issue happening on Safari -> i've created Scrum project, then decided to enable Kaban and disable backlog but I couldn't do that on Safari. Then switched to firefox and disabled without problem ;)

**Comment by macszur-mob** [comment]
Hey,

I've checked what you've asked and here are the results:
- When backlog was disabled in Firefox now I cannot turn it on in Safari, no interesting errors in console tough
- After turning it on in Firefox same story with disabling it on Safari - changing switch to Off doesn't make any difference. No errors in console. 

But just now I found out another thing - clicking other options on "Modules" page doesn't do anything also but if I click all one by one then weird things are happening - suddenly one of the switches switches automatically to off and also - one of selected option really becomes disabled/enabled(I can see addition/removal of icons on the left bar)

I hope that helps ;)

**Comment by juanfran** [comment]
thanks @macszur-mob we've found the problem, it'll be fixed in the next release
