### ISSUE TITLE
Drag and drop for user stories on sprint taskboard not working for public project with 6 members

### ISSUE THREAD

**Issue by nikhidas26** [taigaio/taiga-front#1452]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?**
We have sprints and sprint dashboards, but we are not able to drag them to in-progress or done 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a public project, select scrum
Add 5 members to it
Create a user story
Create a sprint
Add the user story in sprint
Go to sprint taskboard and drag the story to a different status.
We are not able to do it

**What is the expected behavior?**
Users and admin of the project should be able to drag and drop 

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**
Chrome
Version 66.0.3359.139 (Official Build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
https://api.taiga.io/api/v1/user-storage/60df18682b06d61bf7c523d03abaa5a01f37509f 404 (Not Found)

Thanks for reporting!

**Comment by radubcrisan** [comment]
I have the same problem after upgrading 3.3.1

**Comment by nikhidas26** [comment]
What did you do to resolve?

**Comment by flablog** [comment]
Same problem for us. Any update ? :)

**Comment by alexhermida** [comment]
Could you give us more information @nikhidas26 and @flablog ? It's happening in tree.taiga or in your own instance?

The *404* @nikhidas26 commented it's normal and related to user storage data. When you tell us *"Go to sprint taskboard and drag the story to a different status."*, are you refering to *drag tasks* instead of user stories? 

Regardless the issue doesn't seems to happen in production nor in many self-hosted instance because would be an quite important bug. Maybe you can try to give us more detailed information to look for the specific case? The commented steps works well right now in master and stable branches. 

We would be glad to help you :-)

**Comment by flablog** [comment]
Actually we fixed it doing:
- a fresh install of the last release
- and not importing our project (which broke the drag and drop again), and re-creating our open stories...

So something in the exported json project was breaking fresh installs on self hosted instances in our case.

We tried then ton add 20 people to the project, and it was working well

**Comment by poliveira89** [comment]
This is still an issue on version deliver by https://tree.taiga.io

**Comment by alexhermida** [comment]
@poliveira89 we test this issue again following the provided steps, and we couldn't reproduce it. 
Drag and drop user stories on sprint taskboard it's not a feature. You can drag and drop US's on Kanban, or you can drag and drop Tasks in the Taskboard, but you cannot drag and drop US's on taskboard. 
Could you give us additional details of the issue?
