### ISSUE TITLE
Unexpected tooltip on US attachment button

### ISSUE THREAD

**Issue by lhole** [taigaio/taiga-front#591]
Steps to reproduce:
1) Go onto the Kanban within a project
2) Select a US
3) Hover over the plus button to the right of "0 attachments"

Expected outcome:
The tooltip might indicate that the button adds an attachment. It possibly indicates what the maximum file size of the attachment could be.

Actual outcome:
The tooltip contains the message: `Add new attachment. <%- maxFileSizeMsg %>`

Note that the plus button to the right of "Related tasks" has no tooltip on hover, so it might be desirable that these are made consistent.
I'm in the en_GB locale.

**Comment by Xaviju** [comment]
You are right @lhole i think this is a bug! :bug:

**Comment by superalex** [comment]
Fixed here! -> https://github.com/taigaio/taiga-front/commit/f614c3eb196680d81a512743ef9ee8bdba1bb225

Thank you very much @lhole

**Comment by rriemann** [comment]
Has this been merged and put into production at tree.taiga.io ?
I still have this issue: 
![moodle1](https://cloud.githubusercontent.com/assets/111932/10863196/d633f92a-7fc5-11e5-929f-c40e4abd9cec.jpg)

**Comment by superalex** [comment]
Hello @rriemann still not in production but it will be included in the 1.9 release (next week)
